### ISSUE TITLE
Global helper functions naming

### ISSUE THREAD

**Issue by Tynael** [niladam/laravel-visits#1]
Consider adding a `_` at the beginning of the function name (i.e `_visitUrl`) or add a prefix (i.e `lvVisitUrl`).

The function names are pretty common and the chance of having a similar custom global function in a big project is quite high.
Having a distinctive name will ensure that the functions will not collide with the project's own functions.

https://github.com/niladam/laravel-visits/blob/main/src/helpers.php#L10

**Comment by niladam** [comment]
That's a good point. I didn't think of that. 

Let me do this now :)
