### ISSUE TITLE
Consider specifying the 3rd param for in_array()

### ISSUE THREAD

**Issue by Tynael** [niladam/laravel-visits#2]
Consider specifying the 3rd param for the `in_array()` function as it's a good practice to avoid errors caused by different data types.

https://github.com/niladam/laravel-visits/blob/main/src/Models/Visit.php#L80C26-L80C26

`return in_array($this->platform, ['phone', 'tablet'], true);`

If the third parameter is set to true, the comparison is strict. 
This means that PHP will perform a strict comparison (`===`) when searching for the value in the array.
In a strict comparison, not only the values but also the data types must match. 
So, if you search for the integer 5 in an array containing the string "5", in_array() will return false because the data types are different.

**Comment by niladam** [comment]
Thank you. Somehow that slipped my mind when working on it that. I usually do strict checks myself too :)

**Comment by niladam** [comment]
This was fixed in #4
