### ISSUE TITLE
Map platform values in a constant/Enum instead using them as a string

### ISSUE THREAD

**Issue by Tynael** [niladam/laravel-visits#3]
At this moment, the values that are being used as a type for the `platform` attribute in `Model\Visit` are being used as plain strings.

https://github.com/niladam/laravel-visits/blob/main/src/Models/Visit.php#L30

For usability, consider mapping them in a constant or better yet in an `Enum` type of Class.
This way, you avoid string duplications and it will be easier to re-use the code anywhere in the project.

**Comment by niladam** [comment]
Remapping these to an Enum isn't really worth it right now, as the platform comes from the agent package's `deviceType` method. The method's signature is:

```php
    /**
     * Get the device type
     * @param null $userAgent
     * @param null $httpHeaders
     * @return string
     */
    public function deviceType($userAgent = null, $httpHeaders = null)
    {
        if ($this->isDesktop($userAgent, $httpHeaders)) {
            return "desktop";
        } elseif ($this->isPhone($userAgent, $httpHeaders)) {
            return "phone";
        } elseif ($this->isTablet($userAgent, $httpHeaders)) {
            return "tablet";
        } elseif ($this->isRobot($userAgent)) {
            return "robot";
        }

        return "other";
    }
```

This was intentionally left like this since there's no actual gain in introducing a enum.

**Comment by niladam** [comment]
Closing this for now.
