### ISSUE TITLE
Use RecordVisitsMiddleware as an alias for middleware groups

### ISSUE THREAD

**Issue by Tynael** [niladam/laravel-visits#5]
In `src/LaravelVisitsServiceProvider.php` you can register the `RecordVisitsMiddleware` so it can be used as a middleware group for multiple routes.

```
public function boot(Router $router)
{
    $router->middlewareGroup('lv-record-visits', [RecordVisitsMiddleware ::class]);
}
```

Then it can be used as follows:

`Route::middleware(['lv-record-visits'])->group(function () {
    // ...
});`

By using this method, you avoid duplicating the `->middleware(RecordVisitsMiddleware::class)` statement when multiple routes can be under the same group.

**Comment by niladam** [comment]
Somehow i'm finding this basically hides the group behind a string, without allowing you to easily navigate to that.

If someone wants to group, and/or add multiple routes into the same group they can always have it as so:

```php
    Route::middleware([RecordVisitsMiddleware::class])->group(function () {
        Route::get('something', MyController::class)->name('something');
        Route::get('something-else', [AnotherController::class, 'show'])->name('something-else');
    });
```

Also, you can easily add the `RecordVisits` middleware to your 'web' group in `$middlewareGroups` in the `App\Http\Kernel.php` class.

Thank you for your suggestion, but for now, it's not something that i'm planing on doing.
