### ISSUE TITLE
Show Packagist info in the README

### ISSUE THREAD

**Issue by Tynael** [niladam/laravel-visits#6]
```
[![Latest Version on Packagist](https://img.shields.io/packagist/v/niladam/laravel-visits.svg?style=flat-square)](https://packagist.org/packages/niladam/laravel-visits)
[![Total Downloads](https://img.shields.io/packagist/dt/niladam/laravel-visits.svg?style=flat-square)](https://packagist.org/packages/niladam/laravel-visits)
```
The result:

[![Latest Version on Packagist](https://img.shields.io/packagist/v/niladam/laravel-visits.svg?style=flat-square)](https://packagist.org/packages/niladam/laravel-visits)
[![Total Downloads](https://img.shields.io/packagist/dt/niladam/laravel-visits.svg?style=flat-square)](https://packagist.org/packages/niladam/laravel-visits)

**Comment by niladam** [comment]
Closed in #9
